# Generated by Django 5.2.15 on 2026-06-22 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tipotarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('ESPORADICA', 'Esporadica')], max_length=20)),
                ('tipo_dia_vencimento', models.CharField(choices=[('DIA_FIXO', 'Dia fixo'), ('ULTIMO_DIA_MES', 'Ultimo dia do mes'), ('ULTIMO_DIA_UTIL', 'Ultimo dia util do mes')], default='DIA_FIXO', max_length=20)),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('meses_apos_competencia', models.PositiveSmallIntegerField(default=0)),
                ('data_vencimento_esporadica', models.DateField(blank=True, null=True)),
                ('inicio_competencia', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarefas.departamento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarefas.tipotarefa')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['nome'],
            },
        ),
    ]
