# Generated by Django 5.2.15 on 2026-06-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tributacao', models.CharField(choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real'), ('MEI', 'MEI'), ('PF', 'PF')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('baseado_em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_derivados', to='tarefas.planotarefa')),
            ],
            options={
                'verbose_name': 'Plano de tarefas',
                'verbose_name_plural': 'Planos de tarefas',
                'ordering': ['tributacao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTarefaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='tarefas.planotarefa')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Item do plano de tarefas',
                'verbose_name_plural': 'Itens do plano de tarefas',
                'ordering': ['tarefa__tipo__nome', 'tarefa__nome'],
                'constraints': [models.UniqueConstraint(fields=('plano', 'tarefa'), name='unique_tarefa_por_plano')],
            },
        ),
    ]
