# Generated by Django 5.2.15 on 2026-06-22 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_plano_tarefas'),
        ('tarefas', '0004_planotarefa_planotarefaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTarefaAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('ADICIONAR', 'Adicionar tarefa'), ('REMOVER', 'Remover tarefa')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_tarefas', to='empresas.empresa')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Ajuste de tarefa por empresa',
                'verbose_name_plural': 'Ajustes de tarefas por empresa',
                'ordering': ['empresa__nome', 'tarefa__nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tarefa'), name='unique_ajuste_tarefa_por_empresa')],
            },
        ),
    ]
