# Generated by Django 5.2.15 on 2026-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_empresatarefaajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='ajuste_dia_nao_util',
            field=models.CharField(choices=[('MANTER_DATA', 'Manter data'), ('ANTECIPAR', 'Antecipar para dia util anterior'), ('PRORROGAR', 'Prorrogar para proximo dia util')], default='MANTER_DATA', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='dias_antecedencia_alerta',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
