# Generated by Django 5.2.15 on 2026-07-01 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_tarefa_ajuste_dia_nao_util_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='ajuste_dia_execucao_nao_util',
            field=models.CharField(choices=[('MANTER_DATA', 'Manter data'), ('ANTECIPAR', 'Antecipar para dia util anterior'), ('PRORROGAR', 'Prorrogar para proximo dia util')], default='MANTER_DATA', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='controla_execucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='dia_execucao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='dias_antecedencia_alerta_execucao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='meses_apos_competencia_execucao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tarefa_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtarefas', to='tarefas.tarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipo_dia_execucao',
            field=models.CharField(choices=[('DIA_FIXO', 'Dia fixo'), ('ULTIMO_DIA_MES', 'Ultimo dia do mes'), ('ULTIMO_DIA_UTIL', 'Ultimo dia util do mes')], default='DIA_FIXO', max_length=20),
        ),
    ]
