# Generated by Django 5.2.15 on 2026-07-01 16:16

from django.db import migrations, models


def classificar_tarefas_existentes(apps, schema_editor):
    Tarefa = apps.get_model('tarefas', 'Tarefa')

    for tarefa in Tarefa.objects.all():
        if tarefa.tarefa_principal_id:
            tarefa.natureza = 'SUBTAREFA'
        elif tarefa.controla_execucao or Tarefa.objects.filter(tarefa_principal_id=tarefa.pk).exists():
            tarefa.natureza = 'PRINCIPAL'
        else:
            tarefa.natureza = 'SIMPLES'

        tarefa.save(update_fields=['natureza'])


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_tarefa_ajuste_dia_execucao_nao_util_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='natureza',
            field=models.CharField(choices=[('PRINCIPAL', 'Tarefa principal'), ('SIMPLES', 'Tarefa simples'), ('SUBTAREFA', 'Subtarefa')], default='SIMPLES', max_length=20),
        ),
        migrations.RunPython(classificar_tarefas_existentes, migrations.RunPython.noop),
    ]
