# Generated by Django 5.2.15 on 2026-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_tarefa_natureza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='meses_apos_competencia',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Na própria competência'), (1, 'No mês seguinte'), (2, 'Dois meses depois'), (3, 'Três meses depois')], default=0, verbose_name='Mês do vencimento'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='meses_apos_competencia_execucao',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Na própria competência'), (1, 'No mês seguinte'), (2, 'Dois meses depois'), (3, 'Três meses depois')], default=0, verbose_name='Mês de execução'),
        ),
    ]
