# Generated by Django 5.2.15 on 2026-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_alter_tarefa_meses_apos_competencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='meses_apos_competencia',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Na própria competência'), (1, 'No mês seguinte'), (2, 'Dois meses depois'), (3, 'Três meses depois'), (4, 'Quatro meses depois'), (5, 'Cinco meses depois'), (6, 'Seis meses depois'), (7, 'Sete meses depois'), (8, 'Oito meses depois'), (9, 'Nove meses depois'), (10, 'Dez meses depois'), (11, 'Onze meses depois'), (12, 'Doze meses depois')], default=0, verbose_name='Mês do vencimento'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='meses_apos_competencia_execucao',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Na própria competência'), (1, 'No mês seguinte'), (2, 'Dois meses depois'), (3, 'Três meses depois'), (4, 'Quatro meses depois'), (5, 'Cinco meses depois'), (6, 'Seis meses depois'), (7, 'Sete meses depois'), (8, 'Oito meses depois'), (9, 'Nove meses depois'), (10, 'Dez meses depois'), (11, 'Onze meses depois'), (12, 'Doze meses depois')], default=0, verbose_name='Mês de execução'),
        ),
    ]
