# Generated by Django 5.2.15 on 2026-07-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_plano_tarefas'),
        ('tarefas', '0010_alter_tarefa_meses_apos_competencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('data_execucao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_alerta', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('reaberta_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_reabertura', models.TextField(blank=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_concluidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_tarefas', to='empresas.empresa')),
                ('reaberta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_reabertas', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Ocorrencia de tarefa',
                'verbose_name_plural': 'Ocorrencias de tarefas',
                'ordering': ['competencia', 'empresa__nome', 'tarefa__nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tarefa', 'competencia'), name='unique_ocorrencia_tarefa_por_competencia')],
            },
        ),
    ]
