# Generated by Django 5.2.15 on 2026-08-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_organizacao_empresa_organizacao'),
        ('tarefas', '0011_ocorrenciatarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='empresas.organizacao'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('organizacao', 'nome'), name='unique_departamento_por_organizacao'),
        ),
    ]
