# Generated by Django 5.2.15 on 2026-08-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_organizacao_empresa_organizacao'),
        ('tarefas', '0012_departamento_organizacao_alter_departamento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='empresas.organizacao'),
        ),
    ]
