# Generated by Django 5.2.15 on 2026-08-13 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_organizacao_empresa_organizacao'),
        ('tarefas', '0013_alter_departamento_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotarefa',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos_tarefas', to='empresas.organizacao'),
        ),
    ]
