# Generated by Django 5.2.15 on 2026-08-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_organizacao_empresa_organizacao'),
        ('tarefas', '0014_planotarefa_organizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planotarefa',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_tarefas', to='empresas.organizacao'),
        ),
    ]
