# Generated by Django 5.2.15 on 2026-08-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_organizacao_empresa_organizacao'),
        ('tarefas', '0015_alter_planotarefa_organizacao'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planotarefa',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('organizacao', 'tributacao'), name='unique_plano_padrao_por_organizacao_tributacao'),
        ),
    ]
