# Generated by Django 5.2.15 on 2026-06-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_complemento'),
        ('tarefas', '0004_planotarefa_planotarefaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano_tarefas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarefas.planotarefa'),
        ),
    ]
